// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sastreria_data.database;

#nullable disable

namespace sastreria_data.Migrations
{
    [DbContext(typeof(SastreriaContext))]
    [Migration("20241114150747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sastreria_data.database.tables.CategoriaTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("sastreria_data.database.tables.CitaTable", b =>
                {
                    b.Property<int>("idcita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idcita"));

                    b.Property<DateTime>("citafecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("idcliente")
                        .HasColumnType("int");

                    b.Property<int>("idhistorial")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("state")
                        .HasColumnType("bit");

                    b.HasKey("idcita");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("sastreria_data.database.tables.ClienteTable", b =>
                {
                    b.Property<int>("idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idcliente"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idtipodocumento")
                        .HasColumnType("int");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idcliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("sastreria_data.database.tables.DatosTable", b =>
                {
                    b.Property<int>("iddatosastreria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iddatosastreria"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iddatosastreria");

                    b.ToTable("DatoSastreria");
                });

            modelBuilder.Entity("sastreria_data.database.tables.EstadoTable", b =>
                {
                    b.Property<int>("idestado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idestado"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idestado");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("sastreria_data.database.tables.HorarioTable", b =>
                {
                    b.Property<int>("idhorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idhorario"));

                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("horafin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("horainicio")
                        .HasColumnType("time");

                    b.Property<bool>("state")
                        .HasColumnType("bit");

                    b.HasKey("idhorario");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("sastreria_data.database.tables.ModeloImagenTable", b =>
                {
                    b.Property<int>("idmodeloimagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idmodeloimagen"));

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idmodeloimagen");

                    b.ToTable("ModeloImagen");
                });

            modelBuilder.Entity("sastreria_data.database.tables.ModeloTable", b =>
                {
                    b.Property<int>("idmodelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idmodelo"));

                    b.Property<DateTime>("creationdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idcategoria")
                        .HasColumnType("int");

                    b.Property<int>("idmodeloimagen")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idmodelo");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("sastreria_data.database.tables.PedidoTable", b =>
                {
                    b.Property<int>("idpedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idpedido"));

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaentrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("idcliente")
                        .HasColumnType("int");

                    b.Property<int>("idestado")
                        .HasColumnType("int");

                    b.Property<int>("idmodelo")
                        .HasColumnType("int");

                    b.Property<int>("idsastre")
                        .HasColumnType("int");

                    b.HasKey("idpedido");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("sastreria_data.database.tables.SastreTable", b =>
                {
                    b.Property<int>("idsastre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idsastre"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idsastre");

                    b.ToTable("Sastre");
                });

            modelBuilder.Entity("sastreria_data.database.tables.TipoDocumentoTable", b =>
                {
                    b.Property<int>("idtipodocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idtipodocumento"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idtipodocumento");

                    b.ToTable("TipoDocumento");
                });
#pragma warning restore 612, 618
        }
    }
}
